<?php
/**
 * @file
 * Simplenews user list, edit form for adding simplenews category
 *
 * @ingroup simplenews userlist
 */

/**
 * Implements hook_form_alter.
 */
function simplenews_user_list_form_alter(&$form, &$form_state, $form_id) {
 // Add users filters in creation of Newsletter category
 if ($form_id == 'simplenews_admin_category_form') {
  include 'includes/simplenews_user_list.admin.inc';
  $form['user_filter'] = array(
    '#type' => 'fieldset',
    '#title' => t('Create Subscription List'),
    '#collapsible' => FALSE
  );
  
  // This tid repersent the term in Newsletter category vocab,
  // In editing newsletter category, tid repersent the Newsletter Category
  $newsletter_tid = NULL;
  if (isset($form['tid']['#value'])) {
   $newsletter_tid = $form['tid']['#value'];
  }
  // Create user filter based on User account field
  // The id's of form user filter has been set to it's user field ID.
  $users_filters = simplenews_user_list_create_user_filters($newsletter_tid);
  foreach ($users_filters AS $f_key => $f_value) {
   $form['user_filter']['kabootr_user_filter_' . $f_key] = $f_value;
  }
  
  // Create user list based on selected user filters
  $form['#submit'][] = 'simplenews_user_list_admin_category_form_submit';
 }
}

